'use strict';

function stageTextConverter(array) {
  array.push({ grade: 1, stage: 1, text: 'this / that' });
  array.push({ grade: 1, stage: 2, text: 'these / those' });
  array.push({ grade: 1, stage: 3, text: 'What [is / are] ~ ?' });
  array.push({ grade: 1, stage: 4, text: '人称代名詞の主格' });
  array.push({ grade: 1, stage: 5, text: '人称代名詞の所有格' });
  array.push({ grade: 1, stage: 6, text: 'Who [is / are] ~ ?' });
  array.push({ grade: 1, stage: 7, text: '一般動詞' });
  array.push({ grade: 1, stage: 8, text: 'how [many / much] ~' });
  array.push({ grade: 1, stage: 9, text: '人称代名詞の目的格' });
  array.push({ grade: 1, stage: 10, text: '人称代名詞の独立所有格' });
  array.push({ grade: 1, stage: 11, text: '命令文 / Let\'s ~' });
  array.push({ grade: 1, stage: 12, text: 'whose' });
  array.push({ grade: 1, stage: 13, text: 'where' });
  array.push({ grade: 1, stage: 14, text: 'when' });
  array.push({ grade: 1, stage: 15, text: 'which' });
  array.push({ grade: 1, stage: 16, text: 'it' });
  array.push({ grade: 1, stage: 17, text: 'What time ~ ?' });
  array.push({ grade: 1, stage: 18, text: 'how' });
  array.push({ grade: 1, stage: 19, text: 'How [old / tall] ~ ?' });
  array.push({ grade: 1, stage: 20, text: '疑問詞主語のwho' });
  array.push({ grade: 1, stage: 21, text: 'can' });
  array.push({ grade: 1, stage: 22, text: '現在進行形' });
  array.push({ grade: 1, stage: 23, text: 'There [is / are] ~' });
  array.push({ grade: 2, stage: 1, text: '過去形' });
  array.push({ grade: 2, stage: 2, text: '過去進行形' });
  array.push({ grade: 2, stage: 3, text: 'when節' });
  array.push({ grade: 2, stage: 4, text: '一般動詞のSVC' });
  array.push({ grade: 2, stage: 5, text: 'SVO + [to / for]' });
  array.push({ grade: 2, stage: 6, text: 'SVOO' });
  array.push({ grade: 2, stage: 7, text: 'will(単純未来)' });
  array.push({ grade: 2, stage: 8, text: 'will(意志未来)' });
  array.push({ grade: 2, stage: 9, text: 'will(依頼) / shall' });
  array.push({ grade: 2, stage: 10, text: 'be going to' });
  array.push({ grade: 2, stage: 11, text: 'must / may' });
  array.push({ grade: 2, stage: 12, text: 'have to' });
  array.push({ grade: 2, stage: 13, text: 'be able to' });
  array.push({ grade: 2, stage: 14, text: '感嘆文' });
  array.push({ grade: 2, stage: 15, text: '不定詞-名詞的用法' });
  array.push({ grade: 2, stage: 16, text: '不定詞-副詞的用法1' });
  array.push({ grade: 2, stage: 17, text: '不定詞-副詞的用法2' });
  array.push({ grade: 2, stage: 18, text: '不定詞-形容詞的用法' });
  array.push({ grade: 2, stage: 19, text: '動名詞' });
  array.push({ grade: 2, stage: 20, text: '原級比較' });
  array.push({ grade: 2, stage: 21, text: '比較級-er形' });
  array.push({ grade: 2, stage: 22, text: '最上級-est形' });
  array.push({ grade: 2, stage: 23, text: '比較級-more' });
  array.push({ grade: 2, stage: 24, text: '最上級-most' });
  array.push({ grade: 2, stage: 25, text: '比較級-副詞' });
  array.push({ grade: 2, stage: 26, text: '最上級-副詞' });
  array.push({ grade: 2, stage: 27, text: '比較級、最上級の疑問文' });
  array.push({ grade: 2, stage: 28, text: '現在完了-継続' });
  array.push({ grade: 2, stage: 29, text: '現在完了-完了' });
  array.push({ grade: 2, stage: 30, text: '現在完了-経験' });
  array.push({ grade: 2, stage: 31, text: '現在完了進行形' });
  array.push({ grade: 2, stage: 32, text: 'that節' });
  array.push({ grade: 2, stage: 33, text: '受身1' });
  array.push({ grade: 2, stage: 34, text: '受身2' });
  array.push({ grade: 3, stage: 1, text: '従属節を導く接続詞1' });
  array.push({ grade: 3, stage: 2, text: '従属節を導く接続詞2' });
  array.push({ grade: 3, stage: 3, text: '間接疑問文' });
  array.push({ grade: 3, stage: 4, text: '疑問詞 + to不定詞' });
  array.push({ grade: 3, stage: 5, text: '形式主語のit' });
  array.push({ grade: 3, stage: 6, text: 'SVO + to不定詞' });
  array.push({ grade: 3, stage: 7, text: 'SVOC' });
  array.push({ grade: 3, stage: 8, text: '現在分詞修飾' });
  array.push({ grade: 3, stage: 9, text: '過去分詞修飾' });
  array.push({ grade: 3, stage: 10, text: '関係代名詞-主格1' });
  array.push({ grade: 3, stage: 11, text: '関係代名詞-主格2' });
  array.push({ grade: 3, stage: 12, text: '関係代名詞-所有格' });
  array.push({ grade: 3, stage: 13, text: '関係代名詞-目的格1' });
  array.push({ grade: 3, stage: 14, text: '関係代名詞-目的格2' });
  array.push({ grade: 3, stage: 15, text: '関係代名詞-what' });
  array.push({ grade: 3, stage: 16, text: 'too ~ to …' });
  array.push({ grade: 3, stage: 17, text: 'enough ~ to …' });
  array.push({ grade: 3, stage: 18, text: 'so ~ that …' });
  array.push({ grade: 3, stage: 19, text: '原型不定詞-知覚' });
  array.push({ grade: 3, stage: 20, text: '原型不定詞-使役' });
  array.push({ grade: 3, stage: 21, text: '関係副詞-where' });
  array.push({ grade: 3, stage: 22, text: '関係副詞-when' });
  array.push({ grade: 96, stage: 96, text: '中学1年レベルでランダム出題' });
  array.push({ grade: 97, stage: 97, text: '中学2年レベルでランダム出題' });
  array.push({ grade: 98, stage: 98, text: '中学3年レベルでランダム出題' });
  array.push({ grade: 99, stage: 99, text: 'すべての範囲でランダム出題' });
}

module.exports = {
  stageTextConverter: stageTextConverter
};
